# Generated by Django 4.0.4 on 2022-04-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0003_alter_affair_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='affair',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Задание выполнено'),
        ),
    ]
