# Generated by Django 4.0.4 on 2022-04-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0004_affair_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affair',
            name='text',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='affair',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Заголовок'),
        ),
    ]
