# Generated by Django 4.0.4 on 2022-04-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0005_alter_affair_text_alter_affair_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affair',
            options={'ordering': ('-date_add', '-is_completed')},
        ),
    ]
